version = 1
SPDX-PackageName = "variant-forge-api"
SPDX-PackageSupplier = "Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/AliSajid/variant-forge-api"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitleaksignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".markdownlintignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".markdownlint.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".secrets.baseline"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "renovate.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "MIT AND Apache-2.0"

[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["docs/favicon.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["package.json", "pnpm-lock.yaml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Ali Sajid Imami"
SPDX-License-Identifier = "MIT AND Apache-2.0"
